var app = angular.module("site");

app.factory('clanDescriptionsFactory', function(){

  return {
    'Ahrimanes': 'The Ahrimanes are a rare, all-female <termindex term="Bloodline">bloodline</termindex> of <termindex term="Kindred">Kindred</termindex> that originally existed during the Dark Ages, headed by a woman called Ádísa. Sometime during the long night, Ádísa and her <termindex term="Bloodline">bloodline</termindex> were lost and subsumed into <termindex term="Clan">Clan</termindex> Gangrel. Centuries later, the <termindex term="Bloodline">bloodline</termindex> was unknowingly resurrected by a woman called Muricia. Since then, the Ahrimanes roam the night again, albeit under a different guise and leader.',
    'Anda': 'The Anda were a <termindex term="Bloodline">bloodline</termindex> of the Gangrel who existed among the Mongols during the Dark Ages. The <termindex term="Bloodline">bloodline\'s</termindex> progenitor was Dobrul the Brave. The Anda lived openly among their extended families who often acted as their herd. In return for their blood and protection during the day, the Anda would protect the family from harm and use his supernatural powers to the welfare of the family.',
    'Assamite': 'The Assamite <termindex term="Clan">clan</termindex> is based in a hidden fortress named Alamut in the Middle East. They are traditionally seen by Western <termindex term="Kindred">Kindred</termindex> as dangerous assassins and <termindex term="Diablerist">diablerists</termindex>, but in truth they are guardians, warriors and scholars who seek to distance themselves from the <termindex term="Jyhad">Jyhad</termindex>. Throughout their history, they have remained a self-sufficient and independent <termindex term="Clan">clan</termindex>.',
    'Baali': 'The Baali are a <termindex term="Bloodline">bloodline</termindex> of vampires associated with demon worship. Because of their affinity with the unholy, the Baali are particularly vulnerable to holy iconography, holy ground and holy water. Some versions present the true purpose of the Baali as keeping demons sleeping by feeding them with carnage and destruction. But most presentations show them as <termindex term="Infernalist">infernalists</termindex>, using demon worship to gain additional power.',
    'Blood Brothers': 'The Blood Brothers are a rare <termindex term="Bloodline">bloodline</termindex> of the <termindex term="Sabbat">Sabbat</termindex>, created by Tremere <termindex term="Antitribu">antitribu</termindex> and Tzimisce <termindex term="Kolduns">kolduns</termindex>. Designed to function as perfect combat units, Blood Brothers possess a sort of shared consciousness, working exclusively with the \"circle\" of Blood Brothers with whom they share their "hive mind". The members of a circle will often be fleshcrafted by Tzimisce to appear identical, an outward reflection of their lack of individuality.',
    'Brujah': 'The Brujah are a major <termindex term="Clan">clan</termindex> in Vampire: The Masquerade. Quick to anger and always passionate in the Modern Nights, they have been regaining their position as a <termindex term="Clan">clan</termindex> of lofty philosophers and activists, and are often pointed to as a <termindex term="Clan">clan</termindex> of unruly rebels and roughnecks that should not be messed with.',
    'Caitiff': 'Caitiff are vampires with no known <termindex term="Clan">clan</termindex>. It can mean that they were abandoned and therefore do not know their lineage, or that they have no traits of the <termindex term="Clan">clan</termindex> that they were embraced into. Caitiff have no inherent <termindex term="Clan">clan</termindex> <termindex term="Discipline">disciplines</termindex>, but they also do not have any <termindex term="Clan">clan</termindex> weakness. They are typically looked down upon by every other type of vampire, whether it\'s with distaste or pity.',
    'Cappadocian': 'The Cappadocians, also known as the "<termindex term="Clan">Clan</termindex> of Death". Detached scholars obsessed with the mysteries of death, they are now (theoretically) extinct, having been eliminated through a coup de famille by Augustus Giovanni. Unfortunately for the Giovanni, they may have underestimated what it takes to kill a <termindex term="Clan">clan</termindex> of experts on death. It is said that Cappadocius himself developed their unique <termindex term="Discipline">discipline</termindex>, Mortis, which is now known as Necromancy.',
    'Children of Osiris': 'The Children of Osiris are a <termindex term="Bloodline">bloodline</termindex> of vampires who flourished around the second or third millennium BC. The group was founded by Osiris, the \"Resurrected King\". They are known to practice a <termindex term="Discipline">discipline</termindex> unlike any other, called Bardo, which allows a vampire to have control over the <termindex term="Beast">Beast</termindex> within. All their members come from other <termindex term="Clan">clans</termindex>, or are Caitiff. Joining their ranks also requires high levels of <termindex term="Humanity">Humanity.</termindex>',
    'Daughters of Cacophony': 'The Daughters of Cacophony are a <termindex term="Bloodline">bloodline</termindex> of unknown origin (although the most common guesses are Toreador or Malkavian) to the general vampire population. Currently composed entirely of women, the Daughters practice a unique <termindex term="Discipline">discipline</termindex> called Melpominee. This power allows the Daughters to invoke strange effects through singing, and are the choralistes par excellence of the undead, hence their nickname, the "Sirens".',
    'Followers of Set': 'The Followers of Set (or Setites) are a <termindex term="Clan">clan</termindex> of vampires who believe their founder was the Egyptian god Set. Orthodox Setite belief dictates that Set will one day return to rule or consume the world, and devout Setites prepare the way for his resurrection. To this end, the <termindex term="Clan">clan</termindex> remains independent of the <termindex term="Sect">Sects</termindex> of other <termindex term="Kindred">Kindred</termindex>, and practice with great skill the arts of corruption, deceit and ancient sorcery.',
    'Gangrel': 'The Gangrel are one of the thirteen vampire <termindex term="Clan">clans</termindex> found in the Classic World of Darkness, characterized by animalistic features and nature. Nomads who hold closer ties to the wild places than most of their city-bound cousins, they are also closer to the animal aspect of the <termindex term="Beast">Beast</termindex>, and are masters of the Protean <termindex term="Discipline">discipline</termindex>.',
    'Gargoyles': 'The Gargoyles are winged, stony vampires originally created using the blood of three different <termindex term="Clan">clans</termindex>: Gangrel, Nosferatu, and Tzimisce. Created (and enslaved) by the Tremere, they evolved into a full-fledged <termindex term="Bloodline">bloodline</termindex> and became somewhat independent of the Tremere and their blood magic. They employ their own unique <termindex term="Discipline">discipline</termindex> called Visceratika, a power that expresses their natural affinity for stone, earth, and things made thereof.',
    'Giovanni': 'The Giovanni are the usurpers of <termindex term="Clan">Clan</termindex> Cappadocian, and are both a <termindex term="Clan">clan</termindex> and a family. They Embrace exclusively within their family and are heavily focused on the goals of money and necromantic power. They control <termindex term="Wraith">wraiths</termindex> and access the <termindex term="Shadowlands">Shadowlands</termindex> through their unique Necromancy <termindex term="Discipline">discipline</termindex>.',
    'Harbingers of Skulls': 'The Harbingers of Skulls are a rare <termindex term="Bloodline">bloodline</termindex> who surfaced in the Final Nights. While few <termindex term="Kindred">Kindred</termindex> suspect the truth, they are the last remnants of the Cappadocian <termindex term="Clan">clan</termindex>. Usually found among the <termindex term="Sabbat">Sabbat</termindex>, they seek allies in their vendetta against the Giovanni and others who betrayed them.',
    'Kiasyd': 'The Kiasyd are a <termindex term="Bloodline">bloodline</termindex> of the Lasombra founded after a mysterious "accident" involving the Lasombra Marconius of Strasbourg, <termindex term="Fae">faeries</termindex>, and the blood of "Zeernebooch, a god of the underworld". It resulted in The Kiasyd\'s strange alien features and their mystical ties to <termindex term="Changeling">changelings</termindex>.  They practice the unique <termindex term="Discipline">discipline</termindex> Mytherceria, which gives them mystical senses, the ability to steal knowledge, and other powers attributed to <termindex term="Fae">fae</termindex>.',
    'Lamia': 'Lamia was a <termindex term="Bloodline">bloodline</termindex> of the Cappadocian <termindex term="Clan">clan</termindex>, founded after Lamia (a rumored descendant and high priestess of Lilith). Members of this <termindex term="Bloodline">bloodline</termindex> served the Cappadocians as dervishes and warriors until the purge orchestrated by the Giovanni, in 1444. They also practice their own path of Necromancy called "Path of the Four Humors".',
    'Lasombra': 'Leaders of the <termindex term="Sabbat">Sabbat</termindex>, <termindex term="Clan">Clan</termindex> Lasombra are social Darwinists, predators, elegant and inhuman. Due to their inherent <termindex term="Clan">clan</termindex> weakness, Lasombra vampires cast no reflections. They control the shadows using their unearthly trademark <termindex term="Discipline">discipline</termindex>, Obtenebration. Because of their ties to the shadows, they also are more sensitive to light than other <termindex term="Kindred">Kindred</termindex>.',
    'Lhiannan': 'The Lhiannan were a territorial, matriarchal and druidic <termindex term="Kindred">Cainite</termindex> <termindex term="Bloodline">bloodline</termindex> who existed in the Dark Ages. They are an offshoot of <termindex term="Clan">Clan</termindex> Gangrel, although they themselves did not believe they were descended from Caine at all, instead believing they were made by "The Crone". The Lhiannan have a unique connection to the world of spirits, most notably in the form of their <termindex term="Discipline">discipline</termindex> Ogham, a form of blood magic based on Celtic runes.',
    'Malkavian': 'The Malkavians are a <termindex term="Clan">clan</termindex> of <termindex term="Kindred">Kindred</termindex> cursed with insanity, every Malkavian is in some fashion insane. They are one of the original seven <termindex term="Clan">clans</termindex> of the <termindex term="Camarilla">Camarilla</termindex> and a pillar of the organization. Throughout history, the Malkavians have been the seers and oracles of the <termindex term="Kindred">Kindred</termindex>, bound by strange compulsions and insight. The Malkavian\'s <termindex term="Clan">clan</termindex> <termindex term="Discipline">discipline</termindex>, Dementation, is a power that reflects their own madness.',
    'Nagaraja': 'The Nagaraja are a <termindex term="Bloodline">bloodline</termindex> of flesh-eating vampires with a magical heritage. They descend from <termindex term="Mage">mages</termindex> of the Idran faction, part of the Chakravanti Tradition, who sought to create their own brood of vampires by experimenting with vampire blood. The Idran\'s manipulation of vampire blood, combined with their innate magical natures, produced the Nagaraja <termindex term="Bloodline">bloodline</termindex>, feared necromancers, servants of the <termindex term="Black Hand">Black Hand</termindex>.',
    'Nosferatu': 'The most visibly cursed of all <termindex term="Kindred">Kindred</termindex>, the <termindex term="Embrace">Embrace</termindex> warps each Nosferatu into a hideously deformed creature; the archetypal Nosferatu resembles Max Shreck\'s Count Orlok, though the curse has any number of variations. The Nosferatu are the spymasters of the dead, collecting information and selling it for a dear price. They are also the masters of the underground, living in the sewers for protection.',
    'Noiad': 'The Noiad are a Gangrel <termindex term="Bloodline">bloodline</termindex> that dwelled in Finland in the Dark Ages. They are depicted as an alien <termindex term="Bloodline">bloodline</termindex> that may represent the first <termindex term="Kindred">Cainite</termindex> presence on the continent of Europe. As they were extremely dependent on their mortal herds, the Noiads viciously denied any changes in their society, driving them further and further northward to escape the Viking cultures in Scandinavia.',
    'Old Clan Tzimisce': 'The Old Clan Tzimisce are a distinct offshoot of the <termindex term="Tzimisce">Tzimisce</termindex> <termindex term="Clan">clan</termindex> who do not possess Vicissitude, and instead carry on the old ways of using Dominate instead. Typically elders, Old Clan Tzimisce is a representation of what the Tzimisce <termindex term="clan">clan</termindex> was like in the Dark Ages long ago, yet some still remain. They are also the most capable practitioners of <termindex term="Koldunic Sorcery">Koldunic Sorcery</termindex>.',
    'Ravnos': 'Known for being wandering vagabonds and hucksters, the Ravnos are charlatans who gleefully practice their arts of deception and theft. They all have a vice they must compulsively indulge in, which has earned them their seedy reputation. Their signature <termindex term="Discipline">discipline</termindex>, Chimerstry, allows the Ravnos to conjure and control illusions.',
    'Salubri': 'The Salubri are a <termindex term="Clan">clan</termindex> of healers and peacemakers, and bear a distinct third eye on their foreheads. After the <termindex term="Diablerie">diablerie</termindex> of the <termindex term="Clan">clan</termindex> Founder Saulot by the treacherous Tremere, they were hunted down by the Warlocks. They employ two unique <termindex term="Discipline">disciplines</termindex> Obeah and Valeren, for the healer and warrior castes, respectfully.',
    'Samedi': 'The Samedi <termindex term="Bloodline">bloodline</termindex> has a relatively short but immensely curious history within <termindex term="Kindred">Kindred</termindex> society. Originating most likely in the Caribbean, the <termindex term="Bloodline">bloodline</termindex>\'s members all seem to resemble a zombie or a corpse. Unlike the Nosferatu, who merely become disfigured, the body of the Samedi appears to be in a constant state of decay.',
    'Toreador': 'The Toreador are a <termindex term="Clan">clan</termindex> of vampires known for being some of the most beautiful, sensual, seductive, emotional and glamorous of the <termindex term="Kindred">Kindred</termindex>. They are responsible for the legends of vampires who seduce and entice their prey with beauty, love and sensuality. Due to their inherent <termindex term="Clan">clan</termindex> weakness, although lovely and seductive, the members of this <termindex term="Clan">clan</termindex> are as much prisoners of their artistic vision and sensitivity as they are its beneficiaries.',
    'Tremere': 'The Tremere are one of the main bastions of the <termindex term="Camarilla">Camarilla</termindex>, and have their own strict structure and order hierarchy within their own <termindex term="Clan">clan</termindex> as well. Practitioners of blood magic known as Thaumaturgy, they have the most magical heritage, as they became <termindex term="Kindred">Kindred</termindex> through a magical ritual.',
    'True Brujah': 'The True Brujah are a <termindex term="Bloodline">bloodline</termindex> that are the descendants of the original <termindex term="Antediluvian>Antediluvian</termindex> founder of <termindex term="Clan">Clan</termindex> Brujah and not his <termindex term="Diablerist">diablerist</termindex>/<termindex term="Childe">childe</termindex> Troile, hence their name. They are noted for their cool, detached behavior, contrary to the main lineage who are known for their short, violent tempers and rebellious attitudes. They control a unique <termindex term="Discipline">discipline</termindex> known as Temporis, which gives them the ability to manipulate time itself.',
    'Tzimisce': 'The Tzimisce are a <termindex term="Clan">clan</termindex> of scholars and flesh-shapers. The Tzimisce have left the human condition behind gladly, and now focus on transcending the vampiric limitations. Polite, intelligent and inquisitive they seem a stark contrast to the howling <termindex term="Sabbat">Sabbat</termindex> mobs, however on closer inspection it\'s clear this is a mask hiding something alien and monstrous. Their trademark <termindex term="Discipline">discipline</termindex> Vicissitude gives them access to the art of flesh & bone crafting.',
    'Ventrue': 'The Ventrue has long been one of the proudest lines of vampires. Its members work hard to maintain a reputation for honor, genteel behavior, and leadership. A sense of noblesse oblige has long pervaded the <termindex term="Clan">clan</termindex>, accompanied by the genuine belief that the Ventrue know what\'s best for everyone. They consider themselves the oldest <termindex term="Clan">clan</termindex>, and see themselves as the enforcers of tradition and the rightful leaders of <termindex term="Kindred">Kindred</termindex> society.'
  }
});
